# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- hosts: controller_group
  tasks:
  # following roles are not cleaned up directly, they're cleaned when Kubernetes cluster is reset
  # - nfd
  # - multus
  # - sriov/master

  #- include_vars: ./roles/ngc_test/common/defaults/main.yml
  #- include_tasks: ./roles/ngc_test/master/tasks/cleanup.yml

  - include_vars: ./roles/sriov/common/defaults/main.yml
  - include_tasks: ./roles/sriov/common/tasks/cleanup.yml

  - include_vars: ./roles/opae_fpga/master/defaults/main.yml
  - include_tasks: ./roles/opae_fpga/master/tasks/cleanup.yml

  - include_vars: ./roles/cnca/master/defaults/main.yml
  - include_tasks: ./roles/cnca/master/tasks/cleanup.yml

  - include_vars: ./roles/biosfw/master/defaults/main.yml
  - include_tasks: ./roles/biosfw/master/tasks/cleanup.yml

  - include_vars: ./roles/openness/network_edge/master/defaults/main.yml
  - include_tasks: ./roles/openness/network_edge/master/tasks/cleanup.yml

  - include_vars: ./roles/kubeovn/master/defaults/main.yml
  - include_tasks: ./roles/kubeovn/master/tasks/cleanup.yml

  - include_tasks: ./roles/kubernetes/master/tasks/cleanup.yml

  - include_vars: ./roles/kubernetes/common/defaults/main.yml
  - include_tasks: ./roles/kubernetes/common/tasks/uninstall.yml

  - include_vars: ./roles/docker/defaults/main.yml
  - include_tasks: ./roles/docker/tasks/prune.yml
  - include_tasks: ./roles/docker/tasks/uninstall.yml

  - include_vars: ./roles/golang/defaults/main.yml
  - include_tasks: ./roles/golang/tasks/cleanup.yml

  - include_vars: ./roles/git_repo/defaults/main.yml
  - include_tasks: ./roles/git_repo/tasks/cleanup.yml


- hosts: edgenode_group
  serial: 1
  tasks:
  # biosfw/worker - no clean up, because build image is delete when running docker's prune.yml

  - include_vars: ./roles/openness/network_edge/worker/defaults/main.yml
  - include_tasks: ./roles/openness/network_edge/worker/tasks/cleanup.yml

  - include_vars: ./roles/kubeovn/worker/defaults/main.yml
  - include_tasks: ./roles/kubeovn/worker/tasks/cleanup.yml


  - include_vars: ./roles/kubernetes/worker/defaults/main.yml
  - include_tasks: ./roles/kubernetes/worker/tasks/cleanup.yml

  - include_vars: ./roles/kubernetes/common/defaults/main.yml
  - include_tasks: ./roles/kubernetes/common/tasks/uninstall.yml

  # TODO: role: sriov/worker

  - include_vars: ./roles/sriov/common/defaults/main.yml
  - include_tasks: ./roles/sriov/common/tasks/cleanup.yml

  - include_vars: ./roles/opae_fpga/worker/defaults/main.yml
  - include_tasks: ./roles/opae_fpga/worker/tasks/cleanup.yml

  - include_vars: ./roles/docker/defaults/main.yml
  - include_tasks: ./roles/docker/tasks/prune.yml
  - include_tasks: ./roles/docker/tasks/uninstall.yml

  - include_vars: ./roles/golang/defaults/main.yml
  - include_tasks: ./roles/golang/tasks/cleanup.yml

  - include_vars: ./roles/git_repo/defaults/main.yml
  - include_tasks: ./roles/git_repo/tasks/cleanup.yml
