# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- hosts: controller_group
  serial: 1
  roles:
    - role: offline/prepare/before
    - role: os_setup
    - role: golang
    - role: docker
    - role: git_repo
    - role: offline/prepare/yum/prepare
    - role: offline/prepare/get_archives/common
    - role: offline/prepare/git
    - role: offline/prepare/docker_images
    - role: offline/prepare/pip
    - role: offline/prepare/cnca
    - role: offline/prepare/package/ansible
    - role: offline/prepare/package/archive

- hosts: edgenode_group
  serial: 1

  pre_tasks:
  - name: include libvirt vars
    include_vars: ./roles/libvirt/defaults/main.yml

  roles:
    - role: offline/prepare/before
    - role: os_setup
    - role: golang
    - role: docker
    - role: git_repo
    - role: offline/prepare/git
    - role: offline/prepare/docker_images
    - role: offline/prepare/get_golang_modules
    - role: offline/prepare/yum/prepare
    - role: offline/prepare/get_archives/worker
    - role: offline/prepare/pip
    # - role: offline/prepare/hddl
    - role: offline/prepare/package/archive
    - role: offline/prepare/package/experience_kit
    - role: offline/prepare/package/tar
