# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

# Deploy EdgeController on given host(s)

- hosts: controller_group
  serial: 1
  pre_tasks:
  - debug:
      msg: "Setting up {{ inventory_hostname | upper }} at {{ ansible_host }}"
  - fail:
      msg: "Only one controller is supported"
    when:
    - groups['controller_group'] is defined
    - (groups['controller_group']|length>1)
  - include_tasks: ./tasks/precheck_hostname.yml

  roles:
    - role: offline/restore/transfer
      when: offline_mode
    - role: offline/restore/yum/setup
      when: offline_mode
    - role: os_setup
    - role: docker
    - role: git_repo
    - role: golang
    - role: openness/onprem/master
    - role: cnca/onprem
    #- role: ngc_test/onprem/master
    - role: offline/restore/yum/clean
      when: offline_mode
