# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- hosts: controller_group
  tasks:
  #- include_vars: ./roles/ngc_test/common/defaults/main.yml
  #- include_tasks: ./roles/ngc_test/onprem/master/tasks/cleanup.yml

  - include_vars: ./roles/docker/defaults/main.yml
  - include_tasks: ./roles/docker/tasks/prune.yml
  - include_tasks: ./roles/docker/tasks/uninstall.yml

  - include_vars: ./roles/git_repo/defaults/main.yml
  - include_tasks: ./roles/git_repo/tasks/cleanup.yml

  - include_vars: ./roles/cnca/onprem/defaults/main.yml
  - include_tasks: ./roles/cnca/onprem/tasks/cleanup.yml

  - include_vars: ./roles/golang/defaults/main.yml
  - include_tasks: ./roles/golang/tasks/cleanup.yml

- hosts: edgenode_group
  serial: 1
  tasks:
  - include_vars: ./roles/docker/defaults/main.yml
  - include_tasks: ./roles/docker/tasks/prune.yml
  - include_tasks: ./roles/docker/tasks/uninstall.yml

  - include_vars: ./roles/golang/defaults/main.yml
  - include_tasks: ./roles/golang/tasks/cleanup.yml

  - include_vars: ./roles/libvirt/defaults/main.yml
  - include_tasks: ./roles/libvirt/tasks/cleanup.yml

  - include_vars: ./roles/qemu/defaults/main.yml
  - include_tasks: ./roles/qemu/tasks/cleanup.yml

  - include_vars: ./roles/dpdk/defaults/main.yml
  - include_tasks: ./roles/dpdk/tasks/cleanup.yml

  - include_vars: ./roles/git_repo/defaults/main.yml
  - include_tasks: ./roles/git_repo/tasks/cleanup.yml
