# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

# Deploy EdgeNode on given host(s)

- hosts: edgenode_group
  serial: 1
  pre_tasks:
  - debug:
      msg: "Setting up {{ inventory_hostname | upper }} at {{ ansible_host }}"
  - include_tasks: ./tasks/precheck_hostname.yml

  roles:
    - role: offline/restore/transfer
      when: offline_mode
    - role: offline/restore/yum/setup
      when: offline_mode
    - role: os_setup
    - role: os_kernelrt
    - role: dpdk
    - role: golang
    - role: docker
    - role: libvirt
    - role: qemu
    - role: git_repo
    # - role: ovs
    - role: openness/onprem/worker
    # - role: hddl
    - role: offline/restore/yum/clean
      when: offline_mode
