apiVersion: v1
kind: ConfigMap
metadata:
  name: all-config
  namespace: default
data:
  all.conf: |+
    NF_Address =
    {
        AMF_Address = "192.168.102.1";
        SMF_Address = "192.168.102.2";
        UPF_Address = "192.168.102.4";
        PCF_Address = "192.168.102.3";
    };
    CN_Info =
    {
        PLMN = "466.66";
        SliceList =
        (
            {
                Sst = 1;
                Sd = 273;
            },
            {
                Sst = 2;
                Sd = 273;
            },
            {
                Sst = 3;
                Sd = 273;
            },
            {
                Sst = 4;
                Sd = 273;
            }
        );
        AMF_Info =
        {
            AMF_Name = "default.iii.org.tw";
            AMF_Region_ID = 168;
            AMF_Set_ID = 6;
            AMF_Pointer = 48;
        };
        DataNetwork =
        {
            DNN = "Internet";
            UPF_N6_NIC_NAME = "";
        };
    };
    UE_INFO =
    (
        {
            imsi = "466.66.6100000001";
            key =
            {
                k = "00010203.04050607.08090a0b.0c0d0e0f";
                op = "cdc202d5.123e20f6.2b6d676a.c72cb318";
            };
        },
        {
            imsi = "466.66.6100000002";
            key =
            {
                k = "00010203.04050607.08090a0b.0c0d0e01";
                op = "cdc202d5.123e20f6.2b6d676a.11111111";
            };
        },
        {
            imsi = "466.66.6100000003";
            key =
            {
                k = "00010203.04050607.08090a0b.0c0d0e02";
                op = "cdc202d5.123e20f6.2b6d676a.22222222";
            };
        },
        {
            imsi = "466.66.6100000004";
            key =
            {
                k = "00010203.04050607.08090a0b.0c0d0e03";
                opc = "cdc202d5.123e20f6.2b6d676a.33333333";
            };
        },
        {
            imsi = "466.66.6100000005";
            key =
            {
                k = "00010203.04050607.08090a0b.0c0d0e04";
                opc = "cdc202d5.123e20f6.2b6d676a.44444444";
            };
        },
        {
            imsi = "466.66.6100000006";
            key =
            {
                k = "00010203.04050607.08090a0b.0c0d0e0f";
                op = "cdc202d5.123e20f6.2b6d676a.c72cb318";
            };
        },
        {
            imsi = "466.66.6100000007";
            key =
            {
                k = "00010203.04050607.08090a0b.0c0d0e0f";
                op = "cdc202d5.123e20f6.2b6d676a.c72cb318";
            };
        },
        {
            imsi = "466.66.6100000008";
            key =
            {
                k = "00010203.04050607.08090a0b.0c0d0e0f";
                op = "cdc202d5.123e20f6.2b6d676a.c72cb318";
            };
        },
        {
            imsi = "466.66.6100000009";
            key =
            {
                k = "00010203.04050607.08090a0b.0c0d0e0f";
                op = "cdc202d5.123e20f6.2b6d676a.c72cb318";
            };
        },
        {
            imsi = "466.66.6100000010";
            key =
            {
                k = "00010203.04050607.08090a0b.0c0d0e0f";
                op = "cdc202d5.123e20f6.2b6d676a.c72cb318";
            };
        }
    );
