apiVersion: v1
kind: ConfigMap
metadata:
  name: component-config
  namespace: default
data:
  component.conf: |+
    AMF =
    {
        Image = "iii5gc/iiiamf:1.0.3";
        Name = "iiiAMF";
        Ip = "192.168.102.1";
        status = "stop";
    };
    SMF =
    {
        Image = "iii5gc/iiismf:1.0.3";
        Name = "iiiSMF";
        Ip = "192.168.102.2";
        status = "stop";
    };
    PCF =
    {
        Image = "iii5gc/iiipcf:1.0.3";
        Name = "iiiPCF";
        Ip = "192.168.102.3";
        status = "stop";
    };
    UPF =
    {
        Image = "iii5gc/iiiupf:1.0.3";
        Name = "iiiUPF";
        Ip = "192.168.102.4";
        status = "stop";
    };
