# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: Add excludes (rpm packages) to yum.conf
  lineinfile:
    dest: /etc/yum.conf
    line: "{{ os_yum_exclude_rpm_packages }}"
    insertafter: EOF
  when:
    - os_yum_exclude_rpm_packages is defined
    - os_yum_exclude_rpm_packages|bool
