# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

ovn_version: "2.11.4-1"

ovs_package_url: "https://github.com/alauda/ovs/releases/download/v{{ ovn_version }}/openvswitch-{{ ovn_version }}.el7.x86_64.rpm"
ovs_dependencies_yum: "unbound"
ovs_packages_to_remove: "openvswitch,unbound"

kubeovn_cleanup_paths:
- /var/run/openvswitch
- /etc/origin/openvswitch/
- /etc/openvswitch
- /etc/cni/net.d/00-kube-ovn.conflist
