apiVersion: v1
kind: Pod
metadata:
  labels:
    app: upf
  annotations:
    k8s.v1.cni.cncf.io/networks: |
     [
       {
         "name":"sriov-5gc",
         "ips": ["192.168.102.4"],
         "interface": "n3n4"
       },
       {
         "name":"sriov-n6",
         "ips": ["100.86.1.111"],
         "interface": "n6",
         "gateway" : "100.86.1.254"
       }
     ]
  name: upf
spec:
  containers:
  - name: upf
    securityContext:
      privileged: true
    command: [ "/bin/bash", "-ce", "./3.run_UPF.sh && ping localhost" ]
    image: iii5gc/iiiupf:1.0.3
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        intel.com/intel_sriov_netdevice : '2'
        cpu : "1"
      limits:
        intel.com/intel_sriov_netdevice : '2'
        cpu : "1"
        memory: "2G"
    volumeMounts:
    - mountPath: /root/VEPClogs
      name: vepclogs
    
    - mountPath: /usr/etc/all.conf
      name: all-configmap
      subPath: all.conf
    - mountPath: /usr/etc/amf.conf
      name: amf-configmap
      subPath: amf.conf
    - mountPath: /usr/etc/component.conf
      name: component-configmap
      subPath: component.conf
    - mountPath: /usr/etc/dhcpd.conf
      name: dhcpd-configmap
      subPath: dhcpd.conf
    - mountPath: /usr/etc/param.conf
      name: param-configmap
      subPath: param.conf
    - mountPath: /usr/etc/pcf.conf
      name: pcf-configmap
      subPath: pcf.conf
    - mountPath: /usr/etc/smf.conf
      name: smf-configmap
      subPath: smf.conf
    - mountPath: /usr/etc/Quagga.conf
      name: quagga-configmap
      subPath: Quagga.conf
    - mountPath: /usr/etc/upf.conf
      name: upf-configmap
      subPath: upf.conf

  volumes:
  - name: vepclogs
    hostPath:
      path: /home/VEPClogs
      type: DirectoryOrCreate

  - name: all-configmap
    configMap:
      name: all-config
      defaultMode: 0777
  - name: amf-configmap
    configMap:
      name: amf-config
      defaultMode: 0777
  - name: component-configmap
    configMap:
      name: component-config
      defaultMode: 0777
  - name: dhcpd-configmap
    configMap:
      name: dhcpd-config
      defaultMode: 0777
  - name: param-configmap
    configMap:
      name: param-config
      defaultMode: 0777
  - name: pcf-configmap
    configMap:
      name: pcf-config
      defaultMode: 0777
  - name: quagga-configmap
    configMap:
      name: quagga-config
      defaultMode: 0777
  - name: smf-configmap
    configMap:
      name: smf-config
      defaultMode: 0777
  - name: upf-configmap
    configMap:
      name: upf-config
      defaultMode: 0777
