# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: Install required packages
  shell: apt-get install -y jq moreutils


- include_tasks: prebuild.yml
- include_tasks: build.yml
