apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      tolerations:
      - key: node-role.kube-ovn/master
        effect: NoSchedule
      containers:
      - name: producer
        image: producer:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
