apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eaa-prod-cons-policy
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.16.0.0/16
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
